# frozen_string_literal: true

source "https://rubygems.org"

gem "minitest", group: 'development'
gem 'rubocop', group: 'development'
gem "rake", group: 'development'


gem "lazy_priority_queue", "~> 0.1.1"
